name: echoverse
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_lints: ^3.0.2
  anim_search_bar: ^2.0.2
  smooth_page_indicator: ^1.0.0+2
  provider: ^6.0.1
  onesignal_flutter: ^5.1.4
  firebase_core: ^2.10.0
  firebase_messaging: ^14.4.1
  firebase_auth: ^4.4.2
  google_sign_in: ^6.1.0
  sign_in_with_apple: ^6.1.0
  crypto: ^3.0.2
  shared_preferences: ^2.0.9
  flutter_otp_text_field: ^1.1.0+2
  dotted_border: ^2.0.0+2
  audio_video_progress_bar: ^2.0.2
  http: ^1.2.1
  fluttertoast: ^8.0.8
  country_codes: ^2.1.1
  shimmer: ^3.0.0
  webview_flutter: ^4.7.0
  flutter_rating_bar: ^4.0.0
  dio: ^4.0.6
  google_fonts: ^6.2.1
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  dio_logger: ^4.0.8+8
  smooth_star_rating_null_safety: ^1.0.4+2
  progress_dialog_null_safe: ^3.0.0
  miniplayer: ^1.0.1
  just_audio_background: ^0.0.1-beta.9
  just_audio: ^0.9.31
  flutter_locales: ^3.0.1
  intl_phone_field: ^3.1.0
  pinput: ^4.0.0
  readmore: ^3.0.0
  image_picker: ^1.0.7
  path: ^1.8.2
  flutter_pagewise: ^2.0.4
  text_scroll: ^0.2.0
  url_launcher: ^6.1.10
  flutter_share: ^2.0.0

  rxdart: any
  dev_dependencies:
   flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/
    - assets/locales/en.json
    - assets/locales/ar.json
    - assets/locales/hi.json
